
# Introduction {.unnumbered}

## You

You and I:

    0.  **Introduction.** This book is centered on you, the specific reader that you are aware is currently reading. I am the one writing.
    1.  **SELF.** For now, focus on applying these words to your actual [self][SELF], and determining exactly what or who that is.
    2.  **PRI.** Identify and own your [priorities][Priorities] before you die.
    3.  **PPL.** You are not all the other imagined readers. Perhaps they are [people][PPL]. You will be too, but not yet.
    4.  **BET.** First you'll [bet][BET] about who you (think you) are, until you get sick of losing.
    5.  **Education.** At that point you should become [a student][Education] of better methods.
    6.  **WORDs.** As a student you'll simulate methods efficiently with [words].
    7.  **Revision.** You want an answer to the same questions (below) as the rest. [Revise][Revisions] your words until they are uniquely you.
    8.  **COMM.** Then you may contextualize and [communicate][Communication] who you are among people.  
    
Until then, you and I and they are all the same.

## Questions  

Any questions?  

    0.  You. How am I and what do I need?
    1.  Self. What must I do to have it?
    2.  Priorities. What actions maximize my life?
    3.  Others. What are people?
    4.  Bet. How do I take action?
    5.  Learn. How do I figure out a better plan for my life?
    6.  Words. What are they good for?
    7.  Revision. What would my life look like on paper?
    8.  Communication. How do I relate to or help others?  


## Terms  

A book with defined terms is a book for humans.
The following list describes the critical concepts that this book deals with and by impliciation, what it does not deal with.
After each definition is a link to its primary context in the book.
Note that there may be slight discrepancies with definitions in main text as sections become updated. (Last revised: v2.15).

-   A GOAL names an ideal future outcome, and requires a PLAN to intentionally achieve it. ([**c2.38**][Core Concepts])\
-   A PLAN comprises WORDS that facilitate your GOAL. ([**c2.44**][Core Concepts])\
-   A COST is what's materially required for GOALs--an amount and kind of FORCE. ([**c2.49**][Core Concepts])\
-   FOOD is the necessary and sufficient material to satisfy these needs. ([**c2.56**][SELF])\
-   CAKE is all non-FOOD GOALs. ([**c2.57**][SELF])\
-   SELF is the GOAL to MAINTAIN HABIT, ideally to maximize BET outcomes. ([**c2.58**][SELF])\
-   HOME is the collection of tools, materials and money (which support HABITs). ([**c2.59**][Home])\
-   PRI is management of the GOALS in your life (and common themes therein). ([**c3.33**][Attention and time])\
-   PPL are different VERSIONs of each others' PRI (WRITER and READER are different, too).([**c4.1**][PPL])\
-   TIME is the constant (or denominator) for PRI and FORCES (LIB and MEMORY). ([**c3.38**][Attention and time])\
-   MONEY is traded for maintenance of, or insurance for SELF and CAKE. ([**c4.09**][PPL])\
-   WORK is performing a specific task on a collective garden for MONEY. ([**c4.10**][WORK])\
-   NORMS are the "average" person's HABITs, including WORK and CHUD. ([**c4.13**][WORK])\
-   A FORCE is any cause of change including actions. ([**c4.20**][WORK])\
-   MAINTENANCE is any recurring COST to neither move toward nor away from a GOAL. ([**c4.21**][WORK])\
-   An ALIGNMENT is a reduced COST due to a FORCE shared between at least two GOALs. ([**c4.22**][WORK])\
-   A relationship (RLTP) is a GOAL about PPL. ([**c4.23**][WORK])\
-   A BET is a PLAN that leverages TIME against CHUD to facilitate GOALs or a REALITY check. ([c5.28][BET])\
-   CHUD is an acronym for assessing the reality of GOALs: COSTs, HABITs, UNKNOWNs and DOUBTs. ([**c5.41**][C.H.U.D.])\
-   A HABIT is the historical average of your actions and their by-products.([**c5.43**][COSTs and HABITs])\
-   An UNKNOWN is a FORCE (especially out of your CONTROL) that makes your PLAN wrong.([**c5.44**][UNKNOWNs and DOUBTs])\
-   A DOUBT is a source of predictable or nameable UNKNOWN, for example, "denial" or "anxiety". ([**c5.48**][UNKNOWNs and DOUBTs])\
-   A STUDENT is a WRITER sacrificing TIME for concentrated REVISION of their PRIs. ([**c6.15**][Student])\
-   A READER is a WRITER studying their own reaction to and potential use of others' PLANs. ([**c6.39**][READ])\
-   A WRITER invests TIME and energy to map feelings onto WORDS. ([**c6.64**][WRITE PLAN])\
-   An INSTRUCTOR advises and enforces STUDENTs' BETs on PLANs ([**c6.73**][Instructor])\
-   A WORD is a BET for simulating (direct attention to) truth (reality) or falsehood (fantasy). ([**c7.20**][WORD as BET])\
-   An EXAMPLE is an individual, particular event or object of reality. ([**c7.45**][EXAMPLE and IDEA])\
-   A USE-CASE is an EXAMPLE with consequence (vs HYPE). ([**c7.45**][EXAMPLE and IDEA])\
-   A HYPE (hypothetical/hype) is an EXAMPLE in-principle (vs USE-CASE).([**c7.45**][EXAMPLE and IDEA])\
-   A LINK is a WORD that relates at least two EXAMPLES, IDEAS, or describes ACTIONS, ROLES, and transformations. ([**c7.46**][EXAMPLE and IDEA])\
-   An IDEA is a set of criteria that LINKs EXAMPLEs as similar (vs not). ([**c7.46**][EXAMPLE and IDEA])\
-   A PLAN is a BET on a winning arrangement of WORDS that result in the GOAL. ([**c7.23**][WORD as BET])\
-   A SCIENTIST BETs new CONTENT against the UNKNOWN, evaluated for their net gain for NORMs. ([**c7.47**][ROLE Scientist])\
-   A RESEARCHER is a SCIENTIST WRITER, a data-collector and hypothesis tester. ([**c7.48**][ROLE Scientist])\
-   A SCHOLAR is a SCIENTIST READER, curating toward theory development and COMM. ([**c7.49**][ROLE Scientist])\
-   A LESSON is an ordered set of prompts, usually three to four, up to 60 minutes.([**c8.19**][LESSONs])\
-   A NOTE is a general PLAN for REVISION. (Available on request.) ([**c8.33**][NOTES and PEERs])\
-   A RECIPE is a DOC format that PRIs CONTENT (IDEAS and LINKS) over STYLE. ([**c8.37**][DOC types])\
-   COMM is the exchange of WORDS between PPL. ([**c9.45**][STYLE])\
-   VERSIONs are variations of STYLE on a identical CONTENT, implicitly in temporal order. ([**c9.61**][PRIs differ])\
-   A PLAN for a DOC is an earlier VERSION of the (same) final DOC. ([**c9.62**][PRIs differ])\
-   PITCH is DOC STYLE for why to READ. ([**c9.65**][NORMs STYLE])


## Draft  

This is an early copy of Skilled Reflection, and much of it is still in development. Thank you for your patience. I welcome any and all constructive feedback ([skilledreflection\@gmail.com](mailto:skilledreflection@gmail.com){.email}). Check back later for a revised and updated version.


## Version  

When I first set out to write SR as a book I quickly realized a problem could hang me up forever, both simple and superficial.
It is the problem of what order to present the information, so that its truth is easily learnable and most evident.
In Version 1 of this book, I deliberately set aside this problem, in order to name and contain the system of thinking.
Version 2 takes the first step in remediation by streamlining all essential terms and links of the system into a shared frame, called "the Garden" (introduced in version one). Even still, in this respect version 2 is only a working prototype at best.
I pen this Forward at the advent of betting my life on Version 3 (2022-08-30). I cannot promise if / when it will surface, but if you are curious, do not wait. You can find Version 3 already here, between the lines and at their intersections.

## Dear 

Dear, read this book because you're ready to.
You are going to die someday. This book is for you if there is something in the meantime worth maximizing.
Please engage your life. This book is meant to help you understand and take action, starting right now.


## Test  

Please get a pencil and note the date and time, right now: ____________.
The words in this book are meaningful only when you apply them to your life.
If you wrote the date and time as requested, you have proven enough to yourself that you are open to trying new ideas. you are prepared to grow and continue reading.
If you left the line blank, you might tell yourself you are open to new ideas. You will be right when you complete the task.
Either write the time above or stop reading, and take a better action to improve your life, right now.  

## Game  

From now on, every word you (or i) say is a plan for action.
That plan is meaningless until you take that action, whether good or bad.
Therefore, spend less time worrying about why this word or that plan.
Spend more time deciding which will be the next moves in your game of life.  
Sincerely, An0ther  

## Camp  

This book presents plain and obvious facts of life as the antidote to modern complexities of life.
In most cases, the relevance can be seen more clearly if you [simulate][words] the experience being described, or explicitly consider it in your life (see [role of reading][read]). Let's practice. For example, consider going on a camping trip.  

    1. Look at the clock and determine when you should expect to arrive.
    2. Whatever that time, when you arrive, you will likely be over- prepared, under-prepared, or 1-3 hours late.
    3. or you might be an experienced camper.
  
Either way, this is your only shot at a lifelong camping trip for yourself on earth.
My guess is you are very likely late to your own life.
The games we (people, scientists, etc.) play to explain away this fact, end with this book.  

## Pitch  {#intro-pitch}

To understand this book will require you to find and repair the disconnect between your mind's image of time, and the one you are physically bound to.
If you fail, you will die in two worlds, the world you imagine you could have lived, and the one you did.
You, however, would like to ace your own life.
Part one of this book (the garden) gives you all the general answers, and the basic tools for finding the answers particular to you.
Part two teaches you how to (re)build your tools.  


## Eat  

The one thing up to you that this book will not do is draw the line between need and want.
In this book, food refers to needs and cake refers to wants.
You must practice discerning which is which for you, until it is second-nature.
Then, all decisions can be made as follows:  

    1. If hungry, eat food.
    2. If full, prepare and pack food.
    3. If time, eat or prepare cake.

Beware of thinking cake is food.  


## Homeless  

Do, don't think. likely at this point you have slipped into thinking this is a book discussing a philosophy, but it is not.
The difference between food and cake is not understood and solved as a mental exercise in your living room, but by experiencing and paying attention.
What's more, if you don't have a living room, cake can be painfully obvious. be homeless.  


## Food  

The odds are you aren't homeless and will avoid becoming so.
As with any hypothetical, practice finding the nearest analogous, personally meaningful experience:  

    1. You couldn't find your car in the middle of winter.
    2. You went camping without waterproof gear and it rained.
    3. For weeks your shower only produced ice cold water.
    4. You were isolated in your house for most of two years during a global pandemic.  

Whatever the circumstance, your habit protests for a change in plans.
However small or profound the suffering or its threat:  

    1. There is initially terror, frustration and suffering.
    2. Enduring, what you consider suffering will change.
    3. You will need far less food than you thought, giving more time and quality cake you really desire.   
  

## Plan  {#intro-plan}

In the first half of this book is a conceptual metaphor described as a garden.
It is a mental model of reality, designed to bring clarity.
Your garden is your goals put on key ideas of this book.
You need the garden to combat the idealistic side of your mind, inclined to ignore time and your self, which sets you up for failure and suffering.
The second half of these chapters elaborates explicitly on the key ideas.  

## Lessons  {#intro-lessons}

At the end of the book are a series of [lessons][zero or one] for identifying what matters, what's wrong, and what's next in your life.
They are designed to be useful at any time, and especially repeatedly.
Don't wait to finish the book to try one out, because they are pivotal to skilled reflection.
However, don't do too many of them before at least reading the relevant section that explains the format of [skilled reflection][skilled reflection].  

## Definitions  

Pay attention to how words are defined, as it often differs slightly from conventional use.
For example, "work" is an idea referring to "careers", but not 'yard work'.
These nuances are the result of careful decisions about the food and cake of the ideas.
You can find a list of the key ideas in the [index of definitions][index of definitions].
Each chapter deals with a distinct perspective or dimension of life and the goals related to it. what is said is what can be simplified for generalizable guidance.
Like food vs cake, the habits relevant to your goals can be closer to food, or excessive like cake.
In the context of definitions, they will be referred to instead, as "good" and "bad" (for example, [c9.60][pris differ]).
