
# Priorities  


## Calling  

Your calling--your highest priority--is yours to name.
If you overcome your doubts and see reality plainly, you will want peace.
But we all have doubts, so you want some form of dignity and affirmation.
Tell me your calling, student, and subtracting from peace, i'll tell you your doubts.
On mastering my book your life will be regimented to afford your calling.  

Tell me the missing chapter that gives peace instead of regimen, so that i may find mine.

## Cakes

In your garden you have the seeds and sprouts of the best you could want, and the most important of what you need.
There are two important things to keep in mind, however clear things may seem right now.
The first is to always leave room for your goals to change, if and when you achieve them.  think of what you can grow from the seeds of the best apple in your crop.
The second is that much of what you could achieve, you won't, before the day is over, nor before you die.
Before there was a garden, you lived as if you wouldn't die. at least some of your goals assume *tomorrow* is a good time to start.
I did, at least. the list of my goals grew like a wild vine and i found myself overwhelmed by what else i wanted, and yet an inability to equalize various
The very difficult task of your priorities, at their core, is to establish the optimal intersection of finite time and infinite, ever-changing desire.
For example, sleep. about 4 hours daily is a vital priority for everyone (food), but sleeping in on the weekends is usually not (cake).
In your garden, you are limited in what you can do in one day, and in one lifetime.
Even if you build machines to work fields that stretch out to the horizons,
You can only eat so much in a day and a lifetime.
How do you most want to spend your time?
If your goal is to obtain something you do not yet have and have never tasted, be careful. it may not satisfy you how you imagine.
Suppose your goal takes 300 hours of labor.
You might spend 10 years accruing the time on task, or immerse yourself and achieve your goal in under 1 year.
Any true goal has a specific optimal deadline.
Today, you grow the best apple you can,
Yet having tasted it, you might discover a more refined goal is closer to your heart.
Whether this apple is food or cake, the more you align with yourself, the more you will see your goals differently than you first conceived of them.
Leave time in your life to achieve the next goal.  

## Death

Many ppl believe in seeds with special powers, like true love, or winning the lottery.
One seed grows the duration of your life, which you rarely notice but are often aware of.
When you eat it, the sun sets for the last time and you bite the dust. it happens to all of us.
Think about this, but don't dwell on it.  

## Sick  

Maybe you are sick, down or depressed.
Then today, do not look out onto your field as a day to work.
Today your field gives to you, and you should take what you need. this is what it is for.
Do not beat yourself up for what you cannot give today. this assumes your field is only meaningful for its future.
And before you're well again, remember this moment well, so you may
Prevent the urge to be disappointed the next time you are less than productive.
If you must work to feel worthwhile, work to budget for a fact of being human:
You are always sometimes less than productive, and occasionally your setbacks come in unfortunate forms, at inconvenient times.  

## Attention  

Think of what's happening in your garden this very moment: nothing, while you're sitting here thinking.
Reflect only enough to improve your actions.
Pri is the optimizing and managing of all your goals.
All goals rely on a single, limited source of attention, and existence: you.

At its best, this limiting fact drastically improves the reality of plans and goals.
At its worst, it is the most common oversight responsible for bloated [CHUD][c.h.u.d.].

The goal of attention is to think; to link your reality here and now with the word that best moves you toward your priority. 

Goal importance partly depends on context (c3.6).
Group your goals by shared actions, places, or times. make/group/keep,
Align self and cake.
Ask what it would take to change (if possible), and whether change is worth it.
Savings occur anytime you complete an action that serves various goals.
An example is grouping (c3.35.4).
Apply to ideas, plans, goals, or home things.
Time is the constant (or denominator) for forces, forgetting, pri, and lib.
Do not ignore time.
Estimate durations accurately for goal accomplishment.
Study time to learn reality, self, and their link.
Continually assess whether goal benefits outweighs costs of time.
Maybe it seems unnecessary to represent work satisfaction and relationship quality in terms of carrots and tomatoes.
When you get bored, ask yourself why attempting to understand and define yourself bores you.
What is happening in your life, and what is in your control if these are unclear?
If you are not reflecting on your life, your garden is a foggy labyrinth, and you are a drunk gardener wearing oven-mitts.
You are pushed like a sail by any wind, the forces of reality.
A force is any cause of change.
A force underlies every action involved in a goal, yours or otherwise.
There are forces within your control, and forces outside.
Maintenance is the cost of force to neither move toward nor away from a goal.
Alignment is when norm or natural force causes your goal to be more likely. moment
To align is to adjust your goal to be more like another force, usually one acting against your goal.
Study how forces work against you.  

## Now  

Now is the only use-case of shared space, in time.
A moment is any now that is not the latest, either future or past.
A record of now becomes past 'nows' of variable use-case.
That is, we might reflect on the previous nows that we shared.
Note that past nows do not maintain the same level of rigor. they are degraded to hype when mis-replayed, misunderstood, or accessed under changed priorities.
In seeing passage, we might speculate on future nows to be shared.
The discourse of past or future is always at least partially hype, but real (use) when bet on.
