---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

#	Bet  

## Reality

Life is choices over time.
Each commitment is a bet. 
Are you moving toward your priorities?
Will you arrive before you die?

## Bet  {#bet-bet}  
A good bet aligns reality and priorities.

To bet, name:

1. A step toward your priorities.
2. Estimate the chud (see below)
3. Set a deadline.
4. Take the step.

## Win-Lose  

You win if:  

1. You achieve your step before your deadline.
2. You are closer to or have more of your priorities. 

Otherwise, you lost time.

In both cases, study to improve your next bet.

1. Compare your action to your priorities.
2. Compare your estimated and actual chud.
3. Revise your priorities.
4. Start the next bet.  

## Cost  

Everything in life costs time or effort.
You must be in a certain place, take action, and often give up something.
For example, physical effort or money. 

Self is the basic cost of living your life.
Costs against your priorities are the only bad ones.

Costs only pertain to what actually happens. 
To bet requires estimating costs.

## Habits  

Habit is the basic pattern of actions you have taken, 
whether toward your priorities or toward suffering.
Habit is the rational, descriptive summary of your history.
Habit serves as the rational prediction of your bet outcomes.
Regardless of how expensive your habit, a change of habit is always an added and difficult cost.
That is, unless and until the change becomes a habit.

Suppose in the last 3 days I ate at 9 am.
If tomorrow is a day like the last three, habit predicts I will eat before 9 am.
It also predicts that this is the lowest cost action.


## Unknowns  

Unknowns are all that are fully out of your control (i.e., statistical error).
For example, planning a drive that doesn't account for a train crossing delay. 

Unknowns are the difference between your real and estimated costs and habits.
Bet to learn them.


## Doubts  

Imagine achieving all your priorities, right now.
When considering the costs, note to the fears that surface.
Never mind the world, how are you in your own way?
These are doubts.

Doubts are reliable patterns of failure.
See your doubts with curiosity. 

For example:
- self-fulfilled prophesies
- over- or under-estimating habits
- anxiety or insecurity 
- distrust in your past

A strong bet is partly made in terms of what you think holds you back most.
