---
editor_options: 
  markdown: 
    wrap: 72
---

# Words

## Cognition

Words describe the world and its conditions.
Each word is a bet about how the world is or can be,
and by extension, the use of words can be improved.
Better words means:
- more practical understanding and expectations.
- better bets.
- healthier communication and relationships.

## Bet  {#word-bet}

A word is a bet. 
Good words advance good bets. 

Words cost almost nothing but a fraction of a second to make or hear.
Reading, thinking, saying, and writing a word perpetuates that word's idea over others, either moving you toward a goal, or your habit.  
Words said and heard impact both parties' beliefs and behaviors.

Speaking your mind is difficult to do accurately.

Words are good when they prevent or improve actions you would've taken otherwise.
Unfortunately, the norm for unproductive words is tens of thousands per day.
For example, the words in every ad not aligned with your priorities, or thought about a celebrity you will never meet.

## Simulation  
To make good words, understand their unique power.
A word's power is in narrowing attention in infinite ways.
To reliably narrow, a word requires a definition.
A definition is a generalization which depends on examples.
Careful, good words efficiently isolate and simplify alternative choices.
Bad words bring attention to irrelevant generalizations.

A word is good when it leads to better actions.
Therefore, use words to simulate and find such improvements. 
You can think through far more than you can act out.

Words can be easily crossed out and revised.

Good words maximize productivity of thought, move you beyond pitfalls of chud, direct attention to pris, and predict reality; improve decisions and make you smarter.

Simulation is the act of iterating between write and read. 
Word meanings are not limited to reality, but your imagination.

## It  

It (i.e., "reference") is the idea words attempt to bring attention to. 
For example, consider this scenario: 

I wanted to sleep until 9:30 A.M.
I also wanted to know how you are doing.
At 9:00 am you call me and begin to tell me how you are doing.
I yawn.
You say, "I must be boring you."

Each of these (below) are words to say "it", ranked from best to worst:  

    1. You're not, please continue.  
    2. No, I'm tired.  
    3. No, I woke too early.  
    4. Don't make assumptions.  
    5. I'm not.  
    6. I woke at 8:30am, but wanted to sleep until 9:30am, so I think I yawned because I am tired. I can see why you thought I was bored.   

Good words are ones that uses truth to focus and advance communication.
Below are properties that make each choice unique (and less good).

1. Gives a simple, informative reason to return to communicating.
2. Does not add or return to communication priorities. 
3. May not be relevant or true.
4. Focuses on others' mistake and issues a command.
5. Begs the question. I.e., "Then why did you yawn?"
6. Focuses on the distraction and makes the same kind of ref which the other did and which caused the confusion.

## Write {#word-write}  

When you have good words to indicate It, do not hold out for better words.
Quickly name the relevant links for It and estimate the loss.
Repair your words only when they pose a problem to the communication priorities.

It, and the actions behind it are more important than who said what (i.e., authorship).
Say the truth or be quiet.
Resist and ignore politeness and impoliteness.
Use words for decisions, not emotions.
Use words to facilitate priorities.
Do not write plans you won't follow.
Words without plans are fantasy and entertainment. 
To choose words is to not choose to take action in your life.
Stop talking when action (or listening) is needed.  

## Read {#word-read}  

Read when you doubt options available for actions you will take.
Limit the duration or words needed to assess consent. (?)
Distrust ego, and take nothing personally.
Investigate the empirical cake of words.
Ignore style.
Do not let others' words abuse your time or understanding.
Assert boundaries against exaggerated or excessive words.  

## Example  {#word-example}

The real world is particular; each experience is an example.
A word describes a set of similar experiences.
    1.  words are never definite and certain in what they describe of the real world.
    2.  A word's definition is a generalization.
As such, words are
    1.  less precise than reality.
    2.  better designed to hypothesize and predict.

All words take their meaning from an average of examples.
It is an example.
An example is one event or object.
Examples can be real or imagined.
A Use-Case is an example taken from a real experience.
A Hypothetical (Hype) is an example in-principle.

## Meaning  

Words direct attention in one of two ways:
Links are words that give relationship between two directions of attention.
Ideas: words that refer to examples, 
An idea is a set of criteria that link examples as similar (vs different).
The most basic idea classifies examples as "It" or "not It". 
For example, "blue" is simultaneously a specific color and not other colors.

Just as costs are only bad when misaligned with priorities, words are only bad when misaligned with It.

## Hype  

Hype vs use-case guides what and if to write. a goal is a named hype. good hype are worthwhile goals, sub-goals, or alt plan actions to consider. don't write hype without a bet.
As all words should be toward pris, there are three general modes of pri words:
H0 = history. habit is to history as action is to doc. good
H1 = plan (pri.txt, proj_doc.txt)
H2 = doubt especially for bet.  

## Alternatives  {#word-alternatives}

Alts are any idea which measurably deviates a plan, and are defined directly with respect to the target idea.
For example, bad is an alt to good, as in "good-vs-bad".
Any other valid modes, if at all, are in support of maximal revision in these primary ones.
A plan comprises: 1.the decided action 2.the best bet on it
Alternative actions 4.the goal 5.the relevant chud
Good goals and their plans are supported by uses from your own history (self-h), and next best is norm or others' use or data that generalizes.
For example, a plan for a similar goal has previously succeeded.

## Letters  

Mnemonics are letter memory aids.
Reducing a word to a letter increases cognitive efficiency, as long as that letter stands for an idea you will frequently encounter.
These letters illustrate kinds of word usage (not exhaustive):  

`f` define; function\
`i` synonym, sense, "i.e.", "as in",\
`e` example, data-point, untested data\
`h` history (implied h0)
`h1` claim, thesis. vs h0 or h2.
`x` cross-references, xref\
`d` data or evidence, summary
`v` version / revise\
`vs` an alternative, sibling of a shared parent category.  

## Notes  

Good notes clarify pri (content) within bets from secondary ones.
In a doc, par is a grouped set of words roughly equivalent to a complex sentence.
It has a primary subject and predicate, and includes any immediately relevant branches from either.
In practice it is between 1 and 4 clauses.
Good par successfully denotes a link between two ideas, with the following form:
A syntactic tree, where\
[Newline] is the right path in a fork,\
First indent (" -") is the left path in a fork,\
Subsequent newline indents or in-line "--" are siblings\
Left to right are siblings\
Double linebreak ends the local tree.
When word order is a left-to-right walk of a right-branching syntactic tree, sentence can be written in lines of random lengths, and read equally as unambiguously.
Restrict reference and vocabulary to simple- or plain- english to reduce amibiguity.  

## Transparency  

Make folder and file names i-goals as transparent as possible imply or reveal its (hidden) members.
Promote or consolidate high frequency items or only-childs.
For example: `ppl-work -\> work - self-home -\> home`
When creating or reusing a word for new applications, this principle should be a factor.  

## Recipe  

A recipe is one of the best ways to arrange plans.
Lessons and instructions use a recipe format.
The recipe format highlights the ideas and links of your point and minimizes excessive style.
List key ideas.
Describe actions and transformations (links).
Given an idea, estimate relevance to pris, problems, undeveloped plans, and self-maintenance.
Keep docs short enough that the title and content address only one thing.
Save selectively and delete frequently.  

## Document  

A word is a doc when it is saved with a name, at least once.
Notes are words for communication.

Introduce ideas in unambiguous terms.
Introducing a new topic, provide a succinct, distinctive illustration of the point or merit, *in the verbiage you will most likely understand*.
then describe the link with a taxonomic reference, as follows, where each idea read left to right is a type of or label for the preceding category, implying alternatives at each level.
e-psych-teach-2021-unit4-hw-methods_report-intro "for this assignment, consider your grandparents."

latter ideas qualify the topic, psych. the order of terms from left to right should closely correspond to the order of relevant conditional differences that determine: the reader's priorities. 
In the fewest words, help a reader know a topic is irrelevant or truly beneficial?

the most similar and relevant concepts to most distinct, rare, and particular to what is being described.
the left-most word will be either implied or actual chapter headings.

the link is the decision of the sentence that requires the most care. 
it is simply a bridge, and as such has a basic and plain function.
named links are actions.
over-spelling the ideas leaves an empty link, e-"do...(the
trash)" consider what is the manner of spending time, if an
action, to ascribing your link. consider the specific change
being undertaken. some actions: take, give, make, buy, sell,
use/eat, work, write, read. 
- notice these are all verbs of transfer.
in instr, the link comes last, and it describes a step in revision.
contextualize with an alternative
a plan should inherit or give definitions of new terms.
new definitions should especially be accompanied by a true use-case, to protect against a false problem.
a pri is the motive for life, and itself is only a named spending of time.
a developed pri is an instruction.
one generalized is a lesson.

## Scientist  

A scientist works to win bets against the unknown. they are a professional writer, evaluated on two metrics:
For their new content.
The net benefit on goal outcomes.
A scientist-researcher is a writer, a data-collector and hypothesis tester.
A scientist-scholar is a reader, curating toward theory development and communication.
More will be said about scientist more broadly. here we focus strictly on the aspect of a scientist which is to develop the description of the world, properly.  

## Framework  

Framework (frame) is a cluster of definitions.
What metric can be used to compare and test bets on words?
Such a metric requires a general framework for cognition.
This is that general framework.
Just as a child learns skills from "put it in the box" to "put it together," and "solve the problem you creatively set up to solve the impossible," so too the highest cognitive function --these days a cooperative one beyond the speed or control of any individual-- deserves treatment of its abilities and applications in order of processing difficulty and utility; utility in contributing to itself however it sees fit, but especially in its allocation of finite resources.  

## Theory  {#word-theory}

$$ h1 where p = cognition, good.p = p(wit.goal.sort|pri) $$
Cognitive acts should be engaged in as a pyramid of levels (like food pyramid), number of tasks (width of level).
For example, a base height of 4 (levels) = 4 topics on bottom level,
On 2nd, 2 on 3rd and 1 on 4th. where the bottom level is the
For example, assuming a goal, make an action plan (blitz) constrained by number of tasks by type as follows:
Sort (base task)
Name, def, or measure,
Make (minimum viable)
Test (edit, sim, revise)
Use (reliable, helpful)
Additional tasks must "wait" to be addressed until a task of the same level becomes complete and removed from the pyramid, leaving a slot to be replaced.
This is a frame that gives a starting point for assessing how and what optimal capacity and boundaries exist for a human as a cognitive being.
Above is a proposed initial bet, arrived at by sim. here's an example good sim:
Name a pri-scope of irl-events.
For example, tasks may differ in how hard and many times actions
The following properties can be varied by sim. 1-task type
Task-level and task-count
For example, 3 levels starting at 10-count, reducing by 2
The goal of sim is to maximize a bet you take (e.g., vs defining

